name: Security Vulnerability
description: Provide details about a security vulnerability.
labels: security
body:
- type: textarea
  id: version_of_this
  attributes:
    label: What version of dependabot-linguist have you identified a vulnerability in (either the tag, commit hash, or semver)?
  validations:
    required: true
- type: textarea
  id: what
  attributes:
    label: What vulnerability have you discovered? Include any relevant details like a CVE.
  validations:
    required: true
- type: textarea
  id: why
  attributes:
    label: What remediation steps are known, if any.
