# <ecosystem-name>:
# # folder under the folder with the name of the <ecosystem-name>
# # i.e. "abc" traslates to a path of <repo>/smoke-test/<ecosystem-name>/abc/
# - dir: "."
#   validated_directories: # output of directories_per_ecosystem_validated_by_dependabot
#   - "/" # List of dirs that should be mapped to by <ecosystem-name>
#   # Or none (and no validated_directories: key) if there shouldn't be any valid dirs

bundler:
- dir: "."
  validated_directories:
  - "/"
cargo:
- dir: "."
  validated_directories:
  - "/"
composer:
- dir: "."
  validated_directories:
  - "/"
docker:
- dir: "."
  validated_directories:
  - "/"
elm:
- dir: "."
  validated_directories:
  - "/"
github-actions:
- dir: "invalid"
- dir: "yaml"
  validated_directories:
  - "/"
- dir: "workflow"
  validated_directories:
  - "/"
- dir: "both"
  validated_directories:
  - "/"
  - "/yaml"
gitsubmodule:
- dir: "."
  validated_directories:
  - "/"
gomod:
- dir: "."
  validated_directories:
  - "/"
gradle:
- dir: "."
  validated_directories:
  - "/"
maven:
- dir: "."
  validated_directories:
  - "/"
mix:
- dir: "."
  validated_directories:
  - "/"
npm:
- dir: "."
  validated_directories:
  - "/"
  - "/removed"
nuget:
- dir: "."
  validated_directories:
  - "/"
pip:
- dir: "pip-compile"
  validated_directories:
  - "/"
- dir: "pip"
  validated_directories:
  - "/"
- dir: "pipenv"
  validated_directories:
  - "/"
- dir: "poetry"
  validated_directories:
  - "/"
pub:
- dir: "."
  validated_directories:
  - "/"
terraform:
- dir: "."
  validated_directories:
  - "/"
