version: 2
updates:
- package-ecosystem: bundler
  directory: "/bundler"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
- package-ecosystem: cargo
  directory: "/cargo"
  schedule:
    interval: monthly
  open-pull-requests-limit: 7
- package-ecosystem: composer
  directory: "/composer"
  schedule:
    interval: monthly
  open-pull-requests-limit: 7
