version: 2
updates:
- package-ecosystem: bundler
  directory: "/bundler"
  schedule:
    interval: monthly
  open-pull-requests-limit: 20
- package-ecosystem: gradle
  directory: "/gradle"
  schedule:
    interval: monthly
  open-pull-requests-limit: 20
